name: publish

on:
  push:
    branches:
      - develop
      - /^release\/v?(\d|\.)*/
    tags:
      - /v?(\d|\.)*/
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - run: echo ${{ github.ref_type == 'branch'}}
      - run: echo ${{ github.ref == '/refs/heads/develop' }}
      - name: Configure Build
        run: |
          TARGET_ENV=prod
          IMAGE_TAG=`echo "${{ github.ref }}" | cut -d/ -f3`

          if [ "{{ github.ref_type }}" = "branch"  ]; then
             if [ "{{ github.ref }}" = "/refs/heads/develop" }} ]; then
                TARGET_ENV=dev
             else
                IMAGE_TAG=`echo "${{ github.ref }}" | cut -d/ -f4`
                TARGET_ENV=uat
             fi
          fi

          echo $IMAGE_TAG
          echo $TARGET_ENV
