name: publish

on:
  push:
    branches:
      - develop
      - 'release/v?[0-9].[0-9].[0-9]**'
    tags:
      - 'v?[0-9].[0-9].[0-9]**'
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_type }}
      - name: version and env from branch
        if: github.ref_type == 'branch'
        run: |
          IMAGE_TAG=`echo "${{ github.ref }}" | cut -d/ -f3`
          VERSION_TAG=`echo "${{ github.ref }}" | cut -d/ -f4`
          VERSION_TAG=${VERSION_TAG:-$IMAGE_TAG}
          echo "${VERSION_TAG}"
          echo "${IMAGE_TAG}"
      - name: Version and env from tag
        if: github.ref_type == 'tag'
        run: |
          VERSION_TAG=`echo "${{ github.ref }}" | cut -d/ -f3`
          IMAGE_TAG="prod"
          echo "${VERSION_TAG}"
          echo "${IMAGE_TAG}"
      - name: Docker
        run: |
          if [ "${IMAGE_TAG}" = "prod" ]; then
             echo "pull VERSIoN TAG"
          else
             echo "build image for version tag and push"
          fi

          if [ "${VERSION_TAG}" != "${IMAGE_TAG}" ]; then
             echo "add image tag to container and push"
          else
             echo "${VERSION_TAG} = ${IMAGE_TAG}"
          fi
